### ISSUE TITLE
Tabel in Bijlage 2 (Appendix B) te groot

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/Metadata-ISO19115#1]
De tabel in "Bijlage 2: Invulinstructies" (zie: Appendix B) is te groot - versie 1.3.1. Deze tabel is te breed en past niet in de ReSpec-layout waardoor het onleesbaar zou zijn voor gebruikers, daarom is deze tabel weggelaten uit de index.html (voor github.io pagina) en staat het nog wel in de oorspronkelijke mdprofiel-iso19115-respec.html. 

Mogelijke oplossingen:
* opsplitsen van de tabel in kleinere tabellen, hierdoor zou echter het aantal DOM-elementen substantieel toenemen;
* converteren naar images, bij voorkeuer SVG, hiervoor zou een soort zoom/pan-optie noodzakelijk zijn anders is de tabel alsnog onleesbaar (https://github.com/Geonovum/respec/issues/49);
* of de tabel omzetten in tekst.

**Comment by pvgenuchten** [comment]
na overleg toch besloten de tabel ongewijzigd te laten, wordt als nuttig ervaren, in print layout kijken of we die pagina's in landscape uit de printer kunnen laten rollen
