### ISSUE TITLE
Xpath karakterset van de bron is onvolledig

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/Metadata-ISO19115#11]
Zie https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#karakterset-van-de-bron. 
Het Xpath onder de titel is onvolledig, dit zou iets als:
` 
identificationInfo[1]/*/characterSet/@codeListValue
`
moeten zijn

**Comment by thijsbrentjens** [comment]
Correctie: dat moet zijn: 

`identificationInfo[1]/*/characterSet/*/@codeListValue`

**Comment by idevisser** [comment]
We verwijzen in geen enkel ander element in het xpath naar het codelistValue attribuut.
correct xpath is;
identificationInfo[1]/*/characterSet
