### ISSUE TITLE
Codelijst datalicenties: waardes en URIs in Codelijst data licenties letterlijk nemen of niet (vanwege versienummering en https)

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/Metadata-ISO19115#14]
Voor het element Overige beperkingen (https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#overige-beperkingen) is een codelijst datalicenties voorgeschreven: https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#codelist-datalicenties.

Nu vraag ik me een paar dingen af:
1. de URIs bevatten asterisken (\*). Zijn die letterlijk/exact zo bedoeld als waarde in de URI of zijn dat plcaeholders voor het versienummer? M.a.w.: moeten de URIs in metadata documenten eruit zien als:
```http://creativecommons.org/publicdomain/mark/*/deed.nl``` (letterlijk) of ```http://creativecommons.org/publicdomain/mark/1.0/deed.nl```. De voorbeelden gebruiken een asterisk, dus ik ga ervan uit dat de URI letterlijk genomen moeten worden. Alleen betekent dit wel datde metadata geen versienummer bevat van een licentie, wat in bepaalde gevallen wel belangrijk kan zijn.
1. de URIs in de codelijsten gebruiken het schema ```http```. De voorbeelden bevatten ook ```https```. Vanwege het punt hierboven vermoed ik dat URIs letterlijk genomen moeten worden, dus dan zou het ```http``` moeten zijn.

**Comment by thijsbrentjens** [comment]
Aanvullend: het is niet volledig duidelijk of van de codelijst kolom ```waarde``` of ```beschrijving``` gebruikt moeten worden om in te vullen. Op basis van de voorbeelden (waarin staat ```Geen beperkingen```) lijkt het de kolom beschrijving te zijn maar bij andere codelijsten moet juist de kolom ```waarde``` gebruikt worden in het element.

**Comment by idevisser** [comment]
de URIs bevatten asterisken (*). Die zijn bedoeld als placeholders voor het versienummer? M.a.w.: de URIs in metadata documenten zien eruit als:
http://creativecommons.org/publicdomain/mark/1.0/deed.nl.

In de voorbeelden moet het versienummer opgenomen worden.

Ook https moet mogelijk zijn, daarvoor wellicht een noot toevoegen oid.

Van: Thijs Brentjens <notifications@github.com>
Verzonden: maandag 6 augustus 2018 13:51
Aan: Geonovum/Metadata-ISO19115 <Metadata-ISO19115@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [Geonovum/Metadata-ISO19115] URIs in Codelijst data licenties letterlijk nemen of niet (vanwege versienummering en https) (#14)


Voor het element Overige beperkingen (https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#overige-beperkingen) is een codelijst datalicenties voorgeschreven: https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#codelist-datalicenties.

Nu vraag ik me een paar dingen af:

  1.  de URIs bevatten asterisken (*). Zijn die letterlijk/exact zo bedoeld als waarde in de URI of zijn dat plcaeholders voor het versienummer? M.a.w.: moeten de URIs in metadata documenten eruit zien als:
http://creativecommons.org/publicdomain/mark/*/deed.nl (letterlijk) of http://creativecommons.org/publicdomain/mark/1.0/deed.nl. De voorbeelden gebruiken een asterisk, dus ik ga ervan uit dat de URI letterlijk genomen moeten worden. Alleen betekent dit wel datde metadata geen versienummer bevat van een licentie, wat in bepaalde gevallen wel belangrijk kan zijn.
  2.  de URIs in de codelijsten gebruiken het schema http. De voorbeelden bevatten ook https. Vanwege het punt hierboven vermoed ik dat URIs letterlijk genomen moeten worden, dus dan zou het http moeten zijn.

**Comment by idevisser** [comment]
Bedoeling is om zowel de URL naar de licentie als de beschrijving op te nemen. Dat kan in één element als daarvoor de anchor oplossing wordt gebruikt. Als de tekst op dit punt niet duidelijk is, moeten we dit wellicht aanpassen.

Van: Thijs Brentjens <notifications@github.com>
Verzonden: maandag 6 augustus 2018 14:45
Aan: Geonovum/Metadata-ISO19115 <Metadata-ISO19115@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [Geonovum/Metadata-ISO19115] URIs in Codelijst data licenties letterlijk nemen of niet (vanwege versienummering en https) (#14)


Aanvullend: het is niet volledig duidelijk of van de codelijst kolom waarde of beschrijving gebruikt moeten worden om in te vullen. Op basis van de voorbeelden (waarin staat Geen beperkingen) lijkt het de kolom beschrijving te zijn maar bij andere codelijsten moet juist de kolom waarde gebruikt worden in het element.

**Comment by idevisser** [comment]
Het gaat in dit issue inmiddels om 3 punten die aangepast moeten worden;

1. * in voorbeelden omzetten in versienummers
2. verduidelijken dat de beschrijving gebruikt moet worden aanvullend op de URL
3. hoe omgaan met HTTP/HTTPS in waardelijsten

punt 1 en 2 wordt bij het metadata element overige beperkingen aangpast
punt 3 wordt in het algemene deel verduidelijkt onder 3 Structuur en schema's
