### ISSUE TITLE
Overige beperkingen en codelijst LimitationsOnPublicAccess: geldt dit alleen voor INSPIRE metadata?

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/Metadata-ISO19115#21]
Overige beperkingen en codelijst LimitationsOnPublicAccess: geldt dit alleen voor INSPIRE metadata? Onduidelijk in het profiel of dit een eis is voor alle NL metadata. De codelijst is van INSPIRE. Er staat niet bij dat deze codelijst ook verplicht is voor NL metadata. Inhoudelijk zou dat vreemd zijn, omdat er alleen noLimitations is of een bepaalde Europese Directive. Terwijl er voor alleen NL metadata ook andere redenen kunnen zijn om publieke toegang te beperken.

De tekst van het profiel is niet eenduidig over verplichte opname . En voorbeeld 4 bevat geen waarde uit de codelijst. 

Kan dit opgehelderd worden en in het profiel aangepast?

**Comment by thijsbrentjens** [comment]
@pvgenuchten wat is jouw mening over dit punt (als mede editor van het profiel )? Gaat om metadata die niet INSPIRE plichtig is.

**Comment by pvgenuchten** [comment]
Ja, we moeten dit aanpassen in de profiel tekst, de intentie erachter is dat het gebruik van de inspire codelijst LimitationsOnPublicAccess alleen voor inspire datasets verplicht is.

**Comment by thijsbrentjens** [comment]
Dank @pvgenuchten . Ik zal het doorgeven aan de vraagsteller. Laten we het issue maar even open houden, totdat het profiel is aangepast.
