### ISSUE TITLE
Sections Informatief of Normatief

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/Metadata-ISO19115#7]
Momenteel worden alle secties aangeduid als informatief, terwijl sommigen waarschijnlijk ook als normatief moeten worden aangeduid. In ReSpec is het mogelijk om dit op te nemen, bijv.:
```html
<section id="" class="informative">
  .
</section>
```
of:
```html
<section id="" class="normative">
  .
</section>
```

**Comment by lvdbrink** [comment]
Dit is in de huidige gepubliceerde versie niet gedaan.
