### ISSUE TITLE
Missende voorbeelden

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/Metadata-ISO19115#9]
Als gebruiker is het handig om bij in Appendix B: Invulinstructies, een aantal voorbeelden te hebben van de XML structuur. Voor een aantal elementen staan er nu voorbeelden in de HTML, maar de meeste elementen hebben deze nog niet. Nog niet in: 
* [locale](https://geonovum.github.io/Metadata-ISO19115/#locale-appendix-b);
* [role name: referenceSystemInfo](https://geonovum.github.io/Metadata-ISO19115/#role-name:-referencesysteminfo-appendix-b);
* [role name: identificatieInfo](https://geonovum.github.io/Metadata-ISO19115/#role-name:-identificatieinfo-appendix-b);
* [role name: contentInfo](https://geonovum.github.io/Metadata-ISO19115/#role-name:-contentinfo-appendix-b);
* [role name: distributionInfo](https://geonovum.github.io/Metadata-ISO19115/#role-name:-distributioninfo-appendix-b);
* en [role name: dataQualityInfo](https://geonovum.github.io/Metadata-ISO19115/#role-name:-dataqualityinfo-appendix-b).

Voor deze XML voorbeelden kan [Voorbeeld Metadata Dataset](wiki.geonovum.nl/images/Voorbeeld_Metadata_Dataset_2013.zip) worden gebruikt.

HTML-structuur voor een voorbeeld (met HTML entities en pre-tag):
```
<aside class="example" title="XML voorbeeld">
  <pre></code>&ltgmd:MD_Metadata&gt
  &ltgmd:fileIdentifier&gt
    &ltgco:CharacterString&gt550E8400-E29B-11D4-A716-446655440000&lt/gmd:CharacterString&gt
  &lt/gmd:fileIdentifier&gt
&lt/gmd:MD_Metadata&gt</code></pre>
</aside>
```

**Comment by pvgenuchten** [comment]
diverse voorbeelden toegevoegd
